include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [
   temp/**,
   lib/app/app.dart,
   lib/app/app.locator.dart,
   lib/app/app.logger.dart,
   lib/app/app.router.dart
   ]
  errors:
    todo: warning
linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    use_build_context_synchronously: false
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    sort_pub_dependencies: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
