version: '3'
services:
  mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - 'mongodb:/data/db'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/mobile-api
      - NODE_ENV=production
    ports:
      - '3000:3000'
    restart: on-failure
volumes:
  mongodb:
