name: i18n - Upload
on:
  workflow_dispatch:
#   schedule:
#     # runs every weekday at 11:30 AM UTC
#     - cron: '30 11 * * 1-5'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
  CROWDIN_API_URL: "https://freecodecamp.crowdin.com/api/v2/"
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

jobs:
  i18n-upload-files:
    name: Learn
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Generate Crowdin Config
        uses: freecodecamp/crowdin-action@main
        env:
          PLUGIN: "generate-config"
          PROJECT_NAME: "mobile"

      - name: Crowdin Upload
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: true
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: false

          # pull-request
          create_pull_request: false

          # global options
          config: "./crowdin-config.yml"
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true
